# Generated by Django 6.1.1 on 2026-09-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdlEjemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('valor1', models.IntegerField()),
            ],
            options={
                'db_table': 'ejemplo_nombre_tabla',
            },
        ),
    ]
