# Generated by Django 6.1 on 2026-09-07 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
