# Generated by Django 6.1 on 2026-09-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_clasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='clasi',
            field=models.ManyToManyField(related_name='Cursos', to='cursos.clasi'),
        ),
    ]
